### PR TITLE
Ts migration

### PR DESCRIPTION
**Pull request by rscalderon**

### CODE REVIEW

**Review by joie-zhang — APPROVED** [review]
Great work, Rodrigo! Thanks for putting so much thought into proactively driving the TypeScript migration; it really makes a difference in avoiding runtime errors down the road. For future reference, could you please include in the PR description a screen recording demo of the fully-functioning UI from your localhost to confirm that the changes do not break prod? (or, in this case, the dev branch) Tysm! :)

**Comment by rscalderon** [comment]
Hey Joie, that's a great callout! I actually just realized that some of the images and links got mixed up in the migration. Pushing up the change now

**Comment by rscalderon** [comment]
Also, flagging that @sifulsidd's LinkedIn url returns a 404 error. Since it happens in prod too, it seems like he deleted his LI profile

**Comment by rscalderon** [comment]
Since the video is too large, I uploaded to GDrive. The link is below:

https://drive.google.com/file/d/1z0WCrAw6vyz5v6x9Y3V4txi2W4-px9am/view?usp=sharing

**Pull request merged**
